import React from 'react'

export default function App() {
  return (
    <div className="min-h-screen bg-gray-50 flex items-center justify-center p-8">
      <div className="bg-white rounded-2xl shadow-lg p-10 max-w-lg w-full text-center">
        <div className="text-6xl mb-4">🛫</div>
        <h1 className="text-2xl font-bold text-gray-800 mb-2">
          SPO Пульт КК — Внуково
        </h1>
        <p className="text-gray-500 text-sm mb-6">
          Оптимизация совмещения задач SV+GH с контролем нагрузки
        </p>
        <div className="bg-amber-50 border border-amber-200 rounded-lg p-4 text-left">
          <p className="text-amber-800 text-sm font-medium mb-1">
            ⚙️ Требуется настройка
          </p>
          <p className="text-amber-700 text-xs leading-relaxed">
            Для генерации полного приложения добавьте{' '}
            <code className="bg-amber-100 px-1 rounded font-mono">ANTHROPIC_API_KEY</code>{' '}
            в GitHub Secrets и запустите воркфлоу с параметром{' '}
            <code className="bg-amber-100 px-1 rounded font-mono">force_regenerate=true</code>.
          </p>
        </div>
        <p className="text-gray-300 text-xs mt-6">
          Placeholder — generated by agent.py
        </p>
      </div>
    </div>
  )
}
